language: ruby
rvm:
  - 1.9.3
bundler_args: --without development
env:
  - DB=sqlite
  - DB=postgresql
script:
  - bundle exec rspec
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - psql -c 'create database lentlist_test' -U postgres
  - RAILS_ENV=test bundle exec rake db:migrate