language: ruby
rvm:
  - 1.9.3
bundler_args: "--without development metrics"
env:
  - RAILS_ENV=test DB=sqlite
  - RAILS_ENV=test DB=postgresql
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - psql -c 'create database lentlist_test' -U postgres
  - "cp config/database.ci.yml config/database.yml"
  - RAILS_ENV=test bundle exec rake db:migrate