sqlite: &sqlite
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3

postgresql: &postgresql
  adapter: postgresql
  username: postgres
  password:
  database: lentlist_<%= Rails.env %>
  min_messages: ERROR

test:
  <<: *<%= ENV['DB'] || "postgresql" %>
  pool: 5
  timeout: 5000
  host: localhost
